namespace Models {
    export type ActionsLog = {
        id: number;
        user_id: any;
        material_type?: string;
        material_id?: any;
        action: any;
        changes?: any[];
        created_at?: string;
        updated_at?: string;
        action_name: any;
        material: any;
        material_name: any;
        material_type_name: any;
        user?: User;
    };
    export type AdditionalChannel = {
        id: number;
        order: any;
        program_id: any;
        channel_id: any;
        title?: string;
        date_start?: string;
        date_end?: string;
        created_at?: string;
        updated_at?: string;
        channel?: Channel;
    };
    export type Annotation = {
        id: number;
        interprogram_package_id: any;
        title?: string;
        text?: string;
        order?: any;
        created_at?: string;
        updated_at?: string;
        annotation_type?: string;
        annotation_data?: string;
    };
    export type Article = {
        id: number;
        original_id?: any;
        type_id?: any;
        category_id?: any;
        year?: any;
        month?: any;
        day?: any;
        pending: any;
        username?: string;
        title?: string;
        short_content?: string;
        content?: string;
        views: any;
        ip?: string;
        cover?: string;
        cover_text?: string;
        source?: string;
        user_id?: any;
        path?: string;
        created_at?: any;
        updated_at?: string;
        cover_id?: string;
        original_url?: string;
        url?: string;
        can_edit: any;
        fixed_content: any;
        slug: any;
        created_at_original: any;
        cover_url: any;
        comments_count: any;
        comments?: Comment[];
        category?: ArticleCategory;
        user?: User;
        cover_picture?: Picture;
        crossposts?: Crosspost[];
        tags?: Tag[];
        bindings?: ArticleBinding[];
    };
    export type ArticleBinding = {
        id: number;
        article_id: any;
        channel_id?: any;
        program_id?: any;
        name: any;
        article?: Article;
        channel?: Channel;
        program?: Program;
    };
    export type ArticleCategory = {
        id: number;
        original_id: any;
        type_id: any;
        title?: string;
        created_at?: string;
        updated_at?: string;
        url?: string;
        full_url: any;
    };
    export type Award = {
        id: number;
        picture_id: any;
        groups_can_add?: string;
        created_at?: string;
        updated_at?: string;
        picture?: Picture;
        user_awards?: UserAward[];
    };
    export type Channel = {
        id: number;
        name: string;
        created_at?: string;
        updated_at?: string;
        url?: string;
        logo_id?: any;
        description?: string;
        is_regional: any;
        is_abroad: any;
        region?: string;
        date_of_start?: string;
        date_of_closedown?: string;
        is_federal: any;
        pending?: any;
        author_id?: any;
        country?: string;
        city?: string;
        order?: any;
        is_radio: any;
        background?: string;
        views: any;
        can_edit: any;
        base_url: any;
        route_prefix: any;
        full_url: any;
        names_with_logos: any;
        unique_names: any;
        unique_names_list: any;
        all_names_with_main: any;
        page_random_videos_count: any;
        comments?: Comment[];
        records?: Record[];
        programs?: Program[];
        names?: ChannelName[];
        interprogram_packages?: DesignPackage[];
        logo?: Picture;
        additional_programs?: Program[];
        articles?: Article[];
    };
    export type ChannelName = {
        id?: number;
        channel_id: any;
        name: string;
        alternatives?: string[];
        date_start?: Date | string;
        date_end?: Date | string;
        logo_id?: any;
        created_at?: string;
        updated_at?: string;
        comment: string;
        background_color?: string;
        years_range: any;
        channel?: Channel;
        logo?: Picture;
    };
    export type Comment = {
        id: number;
        material_type: any;
        material_id: any;
        username?: string;
        name?: string;
        email?: string;
        ip_address?: string;
        text?: string;
        rating: any;
        user_id?: any;
        parent_id?: any;
        created_at?: any;
        updated_at?: string;
        original_text?: string;
        can_edit: any;
        can_delete: any;
        text_without_tags: any;
        url: any;
        total_rating: any;
        user?: User;
        new_rating?: CommentRating[];
    };
    export type CommentRating = {
        id: number;
        comment_id: any;
        user_id: any;
        weight?: any;
        created_at?: string;
        updated_at?: string;
    };
    export type Crosspost = {
        id: number;
        article_id: any;
        crosspost_id: number;
        network: string;
        created_at?: string;
        updated_at?: string;
        picture?: string;
        link?: string;
        text?: string;
    };
    export type DesignPackage = {
        id: number;
        channel_id?: any;
        name?: string;
        description?: string;
        author?: string;
        created_at?: string;
        updated_at?: string;
        date_start?: string;
        date_end?: string;
        views: any;
        cover_id?: any;
        program_id?: any;
        url?: string;
        pending: any;
        cover: any;
        one_cover: any;
        random_pictures: any;
        years_range: any;
        can_edit: any;
        full_url: any;
        full_name: any;
        cover_picture?: Picture;
        channel?: Channel;
        program?: Program;
        pictures?: DesignPackagePicture[];
        records?: Record[];
        annotations?: Annotation[];
    };
    export type DesignPackagePicture = {
        id: number;
        package_id: any;
        picture_id: any;
    };
    export type EmailChange = {
        id: number;
        user_id: any;
        email: string;
        code: string;
        created_at?: string;
        updated_at?: string;
    };
    export type Forum = {
        id: number;
        parent_id?: any;
        state: number;
        title: string;
        description?: string;
        topics_count: any;
        replies_count: any;
        last_reply_at?: string;
        can_post?: string;
        can_create_topics?: string;
        can_view?: string;
        last_username?: string;
        last_topic_id?: any;
        last_topic_name?: string;
        created_at?: string;
        updated_at?: string;
        is_closed: any;
        can_create_new_topic: any;
        is_read: any;
        subforums?: Forum[];
        topics?: ForumTopic[];
        fixed_topics?: ForumTopic[];
        not_fixed_topics?: ForumTopic[];
    };
    export type ForumMessage = {
        id: number;
        topic_id: any;
        forum_id?: any;
        is_first: any;
        content?: string;
        username?: string;
        edited_by?: string;
        edited_at?: string;
        ip?: string;
        questionnaire?: string;
        user_id?: any;
        created_at?: any;
        updated_at?: string;
        created_at_ts: any;
        original_text: any;
        can_edit: any;
        can_delete: any;
        user?: User;
        topic?: ForumTopic;
    };
    export type ForumTopic = {
        id: number;
        forum_id: any;
        is_poll: any;
        is_fixed: any;
        is_closed: any;
        first_message_fixed: any;
        last_reply_at?: string;
        answers_count: any;
        views_count: any;
        title: string;
        description?: string;
        topic_starter_id?: any;
        topic_starter_username?: string;
        topic_last_username?: string;
        created_at?: string;
        updated_at?: string;
        last_reply_at_ts: any;
        can_edit: any;
        can_delete: any;
        is_read: any;
        forum?: Forum;
        questionnaire_data?: Questionnaire;
    };
    export type ForumTracking = {
        id: number;
        user_id: any;
        entity_id: any;
        is_forum: any;
        timestamp: any;
    };
    export type Genre = {
        id: number;
        url?: string;
        name?: string;
        type?: string;
        name_pattern?: string;
        records?: Record[];
    };
    export type HistoryEvent = {
        id: number;
        user_id?: any;
        date: string;
        date_end?: string;
        title: string;
        description?: string;
        cover_id?: any;
        created_at?: string;
        updated_at?: string;
        url?: string;
        views: any;
        pending: any;
        short_description?: string;
        can_edit: any;
        date_formatted: any;
        full_url: any;
        blocks?: HistoryEventBlock[];
        cover_picture?: Picture;
    };
    export type HistoryEventBlock = {
        id: number;
        event_id: any;
        video_ids: string;
        order?: any;
        description?: string;
        created_at?: string;
        updated_at?: string;
    };
    export type Page = {
        id: number;
        title: string;
        url?: string;
        content?: string;
        can_read: string;
        last_updated_by?: string;
        created_at?: string;
        updated_at?: string;
        views: any;
        full_url: any;
    };
    export type Picture = {
        id: number;
        created_at?: string;
        updated_at?: string;
        user_id?: any;
        url?: string;
        type?: string;
        channel_id?: any;
        tag?: string;
    };
    export type PrivateMessage = {
        id: number;
        title?: string;
        text: string;
        from_id: any;
        to_id: any;
        is_read: any;
        is_deleted_sender: any;
        is_deleted_receiver: any;
        created_at?: any;
        updated_at?: string;
        is_group?: any;
        group_ids?: string;
        read_ids?: string;
        deleted_ids?: string;
        is_unread: any;
        is_out: any;
    };
    export type Program = {
        id: number;
        channel_id?: any;
        cover: string;
        name: string;
        created_at?: string;
        updated_at?: string;
        url?: string;
        cover_id?: any;
        description?: string;
        date_of_start?: string;
        date_of_closedown?: string;
        genre_id?: any;
        pending?: any;
        author_id?: any;
        order?: any;
        views: any;
        show_full_titles: any;
        can_edit: any;
        full_url: any;
        random_pictures: any;
        cover_url: any;
        channels_names_list: any;
        channels_history: any;
        cover_without_empty: any;
        unique_names: any;
        records?: Record[];
        cover_picture?: Picture;
        channel?: Channel;
        comments?: Comment[];
        genre?: Genre;
        design?: Record[];
        additional_channels?: AdditionalChannel[];
        interprogram_packages?: DesignPackage[];
        articles?: Article[];
    };
    export type Questionnaire = {
        id: number;
        topic_id: any;
        title?: string;
        multiple_variants: any;
        total_answers: any;
        variants?: QuestionnaireVariant[];
    };
    export type QuestionnaireAnswer = {
        id: number;
        user_id: any;
        variant_id: any;
        created_at?: string;
        updated_at?: string;
        questionnaire_id?: any;
    };
    export type QuestionnaireVariant = {
        id: number;
        questionnaire_id: any;
        order: any;
        title?: string;
        initial_count: any;
        answers_count: any;
        answers?: QuestionnaireAnswer[];
    };
    export type Record = {
        id: number;
        is_from_ucoz: any;
        original_added_at?: string;
        author_username?: string;
        author_id?: any;
        title?: string;
        description?: string;
        short_contents?: string;
        embed_code?: string;
        views: any;
        original_url?: string;
        year?: any;
        year_start?: any;
        year_end?: any;
        month?: any;
        day?: any;
        date?: string;
        channel_id?: any;
        program_id?: any;
        short_description?: string;
        ucoz_id?: any;
        ucoz_url?: string;
        cover?: string;
        is_interprogram: any;
        created_at?: any;
        updated_at?: string;
        cover_id?: any;
        interprogram_package_id?: any;
        is_advertising: any;
        order?: any;
        is_radio?: any;
        url?: string;
        source?: string;
        length?: any;
        original_cover?: string;
        is_clip: any;
        use_own_player: any;
        source_type?: string;
        source_path?: string;
        interprogram_type?: string;
        cut_from_id?: any;
        advertising_brand?: string;
        region?: string;
        country?: string;
        advertising_type?: any;
        supposed_date?: string;
        internal_order: any;
        is_selected: any;
        pending: any;
        other_category_id?: any;
        list_visibility_status: any;
        telegram_id?: string;
        temp_hide_own_player: any;
        external_id?: string;
        description_with_timecodes: any;
        description_topics: any;
        title_without_tags: any;
        program_name: any;
        route_prefix: any;
        broadcast_date: any;
        parsed_short_description: any;
        can_edit: any;
        can_delete: any;
        original_added_at_ts: any;
        short_title: any;
        formatted_duration: any;
        embed_youtube_id: any;
        interprogram_name: any;
        source_audio: any;
        source_hls: any;
        download_url: any;
        source_telegram: any;
        all_telegram_sources: any;
        all_telegram_thumbs: any;
        channel_name_data: any;
        channel_name: any;
        channel_logo: any;
        user?: User;
        channel?: Channel;
        program?: Program;
        cover_picture?: Picture;
        comments?: Comment[];
        interprogram_package?: DesignPackage;
        interprogram_type_data?: Genre;
        advertising_type_data?: Genre;
    };
    export type Smile = {
        id: number;
        picture_id: any;
        text: string;
        show_in_panel: any;
        created_at?: string;
        updated_at?: string;
        picture?: Picture;
    };
    export type SocialPost = {
        id: number;
        user_id: any;
        post_data: string;
        post_ts?: any;
        created_at?: string;
        updated_at?: string;
        post_data_old?: string;
        cover: any;
        title: any;
        post_time: any;
        post_time_iso: any;
        post_connections?: SocialPostConnection[];
    };
    export type SocialPostConnection = {
        id: number;
        crosspost_id: any;
        status: any;
        service: string;
        error_log?: string;
        post_ids?: string;
        created_at?: string;
        updated_at?: string;
        last_data?: string;
        media_data?: string;
        links: any;
    };
    export type Tag = {
        id: number;
        name: string;
        url?: string;
    };
    export type TagMaterial = {
        id: number;
        tag_id: any;
        material_id: any;
        material_type: string;
    };
    export type Teletext = {
        id: number;
        description?: string;
        quality: any;
        channel_id: any;
        author_id?: any;
        pending: any;
        pages?: string;
        year?: any;
        month?: any;
        day?: any;
        date?: string;
        cover_id?: any;
        views: any;
        created_at?: string;
        updated_at?: string;
        author_username?: string;
        can_edit: any;
        url: any;
        cover: any;
        date_formatted: any;
        title: any;
        channel_name_data: any;
        channel_name: any;
        channel_logo: any;
        comments?: Comment[];
        user?: User;
        cover_picture?: Picture;
        channel?: Channel;
    };
    export type User = {
        id: number;
        name: string;
        email_verified_at?: string;
        created_at?: any;
        updated_at?: string;
        username: string;
        original_id?: any;
        ucoz_uid?: number;
        avatar_id?: any;
        group_id: any;
        user_comment?: string;
        signature?: string;
        was_online?: string;
        is_verified: any;
        telegram_id?: string;
        reputation_number: any;
        ban_level: any;
        url: any;
        group_icon: any;
        can_change_reputation: any;
        created_at_orig: any;
        signature_original: any;
        forum_messages_count: any;
        avatar?: Picture;
        meta?: UserMeta;
        reputation?: UserReputation[];
        awards?: UserAward[];
        warnings?: UserWarning[];
        forum_messages?: ForumMessage[];
        comments?: Comment[];
        videos?: Record[];
        group?: UserGroup;
    };
    export type UserAward = {
        id: number;
        from_id: any;
        to_id: any;
        award_id: any;
        comment?: string;
        created_at?: any;
        updated_at?: string;
        from?: User;
        to?: User;
        award?: Award;
    };
    export type UserGroup = {
        id: number;
        name: string;
        icon?: string;
        created_at?: string;
        updated_at?: string;
        icon_id?: string;
        icon_svg_code?: string;
    };
    export type UserGroupConfig = {
        id: number;
        group_id: any;
        option_name: string;
        option_value: any;
    };
    export type UserMeta = {
        id: number;
        user_id: any;
        gender: any;
        yandex_video: string;
        youtube: string;
        country: string;
        city: string;
        vk: string;
        facebook: string;
        date_of_birth?: string;
        date_of_birth_ts: any;
        date_of_birth_formatted: any;
    };
    export type UserReputation = {
        id: number;
        from_id: any;
        to_id: any;
        weight: any;
        comment?: string;
        link?: string;
        created_at?: string;
        updated_at?: string;
        reply_comment?: string;
        from?: User;
        to?: User;
    };
    export type UserWarning = {
        id: number;
        from_id: any;
        to_id: any;
        weight: any;
        comment?: string;
        created_at?: string;
        updated_at?: string;
        time_expires?: any;
        is_forever: any;
        from?: User;
        to?: User;
    };
    export type VideoCut = {
        id: number;
        video_id: any;
        download_status: any;
        download_path?: string;
        data: string;
        created_at?: string;
        updated_at?: string;
        frames?: any;
        fps?: any;
        channel_id?: any;
        year?: any;
        video?: Record;
    };
}
